version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "8000:4566"
    environment:
      - DEFAULT_REGION=sa-east-1
    volumes: 
      - ./init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock