version: "2"

services:
  orders-aws:
    build:
      context: ./target/docker/orders-aws
    image: weaveworksdemos/orders-aws
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
    ports:
      - "8000:80"
    links:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
  dynamo:
    image: amazon/dynamodb-local
    command: "-sharedDb"
    hostname: dynamo
    restart: always
    environment:
      - reschedule=on-node-failure
  init-dynamo:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name chaves-pix --attribute-definitions AttributeName=codigo_banco,AttributeType=S AttributeName=cpf_valor_chave,AttributeType=S AttributeNeme=valor_chave,AtributeType=S --key-schema AttributeName=codigo_banco,KeyType=HASH AttributeName=cpf_valor_chave,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --global-secondary-indexes "[{\"IndexName\": \"ChavePix-index\",\"KeySchema\": [{\"AttributeName\":\"valor_chave\",\"KeyType\":\"HASH\"}],\"Projection\":{\"ProjectionType\":\"INCLUDE\",\"NonKeyAttributes\":[\"codigo_banco\",\"cpf\"]},\"ProvisionedThroughput\": {\"ReadCapacityUnits\": 1,\"WriteCapacityUnits\": 1}}]" --endpoint-url http://dynamo:8000"
    links:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=sa-east-1
