## Banco de Dados DynamoDB
aws:
  access:
    key:
      id: idAWSDynamoDB
      secret: secretAWSDynamoDB
dynamodb:
  service:
    region: us-east-1
    endpoint: http://localhost:8000


  index:
    chave-pix: ChavePix-index

## KAFKA
topic:
  name:
    retorno:
      success: topico-retorno-cadastro-chave-pix-ok
      fail: topico-retorno-cadastro-chave-pix-falha
    envio: topico-envio-cadastro-chave-pix


## Kafka Producer
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
## Kafka Consumer
    consumer:
      group-id: group-bacen
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    listener:
      ack-mode: MANUAL