## Banco de Dados DynamoDB
aws:
  access:
    key:
      id: idAWSDynamoDB
      secret: secretAWSDynamoDB
dynamodb:
  service:
    region: us-east-1
    endpoint: http://dynamodb:4566

  index:
    chave-pix: ChavePix-index

## KAFKA
topic:
  name:
    pix:
      key:
        receive: topico-envio-cadastro-chave-pix
        send:
          success: topico-retorno-cadastro-chave-pix-ok
          failure: topico-retorno-cadastro-chave-pix-falha

      transfer:
        receive: topico-pagador-envio-transacao-pix

        sender:
          finalization:
            success: topico-pagador-retorno-transacao-pix-ok
            failure: topico-pagador-retorno-transacao-pix-falha

        receiver:
          validation: topico-recebedor-envio-transacao-pix
          finalization:
            success: topico-fim-transacao-pix-ok
            failure: topico-fim-transacao-pix-falha

        validation:
          success: topico-recebedor-retorno-transacao-pix-ok
          failure: topico-recebedor-retorno-transacao-pix-falha




## Kafka Producer
spring:
  kafka:
    producer:
      bootstrap-servers: http://kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
## Kafka Consumer
    consumer:
      group-id:
        key: bacen-key-registration
        transfer:
          receive: bacen-transfer
          success: bacen-transfer-success
          failure: bacen-transfer-failure
      bootstrap-servers: http://kafka:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    listener:
      ack-mode: MANUAL